
const ScotlandSEOContent = () => {
  return (
    <div className="sr-only">
      <h2>Event Medical Services Scotland - Complete Coverage</h2>
      <p>Excel Medical Solutions provides professional event medical cover, ambulance hire, first aid services and paramedic support across Scotland including:</p>
      <p>Event medical Edinburgh, first aid Glasgow, ambulance hire Aberdeen, paramedic services Dundee, event medical Stirling, first aid Perth, ambulance hire Inverness, medical cover Kirkcaldy, event medical Dunfermline, first aid Ayr, ambulance hire Paisley, paramedic services East Kilbride, event medical Livingston, first aid Hamilton, ambulance hire Cumbernauld, medical cover Kilmarnock, event medical Coatbridge, first aid Greenock, ambulance hire Glenrothes, paramedic services Airdrie, event medical Falkirk, first aid Motherwell, ambulance hire Wishaw, medical cover Rutherglen, event medical Cambuslang, first aid Bearsden, ambulance hire Newton Mearns, paramedic services Bishopbriggs, event medical Musselburgh, first aid Arbroath, ambulance hire Elgin, medical cover Dumfries, event medical Bathgate, first aid Renfrew, ambulance hire Alloa, paramedic services Bellshill, event medical Blantyre, first aid Dumbarton, ambulance hire Grangemouth, medical cover Larkhall, event medical Johnstone, first aid Port Glasgow, ambulance hire Penicuik, paramedic services Easterhouse, event medical St Andrews, first aid Montrose, ambulance hire Forfar, medical cover Inverurie, event medical Nairn, first aid Prestonpans, ambulance hire Dalgety Bay, paramedic services Carnoustie, event medical Erskine, first aid Linlithgow, ambulance hire Bonnyrigg, medical cover Broxburn, event medical Kelso, first aid Galashiels, ambulance hire Peebles, paramedic services Hawick, event medical Selkirk, first aid Jedburgh, ambulance hire Melrose, medical cover Eyemouth, event medical Duns, first aid Coldstream, ambulance hire Lauder, paramedic services Oban, event medical Fort William, first aid Mallaig, ambulance hire Portree, medical cover Stornoway, event medical Lerwick, first aid Kirkwall, Scotland first aid, Scottish ambulance hire, Highlands medical cover, Islands event medical, Lowlands first aid, Central Scotland ambulance hire, Edinburgh Festival medical cover, Glasgow event medical, Royal Edinburgh Military Tattoo first aid, Highland Games ambulance hire, Scottish football medical cover, rugby event medical, Celtic Park first aid, Hampden Park ambulance hire, Murrayfield medical cover, Scottish Open event medical, Burns Night first aid, Hogmanay ambulance hire, St Andrews golf medical cover.</p>
    </div>
  );
};

export default ScotlandSEOContent;
