// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czjfyffpvcmrxpvnynqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6amZ5ZmZwdmNtcnhwdm55bnFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NjM0ODEsImV4cCI6MjA2NjQzOTQ4MX0.mZqdBb_HFIKvQ7yIKVVzvjPf2xckPseM2EgAJhcixTQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);